//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIproyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string ubicacion { get; set; }
        public string tipoevento { get; set; }
        public int idCliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
